ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "sleepHours" DOUBLE PRECISION;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "exercisedToday" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "frictionToday" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "frictionNote" TEXT;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "positiveMemory" TEXT;
